name: Deploy to cPanel

on:
  push:
    branches:
      - master  # Adjust to match your branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          cp .github/workflows/config ~/.ssh/config
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa 103.57.221.50 >> ~/.ssh/known_hosts

      - name: Test SSH connection
        run: ssh chung_panel hostname
      - name: Push to cPanel Git
        run: |
          git remote add testci chung_panel:/home/webv3/public_html/cicd.chungpq.id.vn
          git push testci master
